operator:
  # image of istio-ratelimit-operator
  image: "docker.repository.mark43.io/istio-ratelimit-operator"
  # tag of istio-ratelimit-operator image
  tag: "v2.14.0"
  # number of replica for deployment
  replica: 1

resources:
  limits:
    cpu: 512m
    memory: 512Mi
  requests:
    cpu: 256m
    memory: 256Mi

settings:
  ratelimitservice:
    image: envoyproxy/ratelimit:91484c59
  statsdExporter:
    image: prom/statsd-exporter:v0.26.1

serviceAccount:
  imagePullSecrets: []

extraLabels: {}

serviceMonitors: true
