apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-manager-role
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "istio-ratelimit-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    manager: {{ .Release.Service }}
    {{- include "istioratelimitoperator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - globalratelimitconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - globalratelimitconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - globalratelimitconfigs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - globalratelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - globalratelimits/finalizers
  verbs:
  - update
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - globalratelimits/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - ratelimitservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - ratelimitservices/finalizers
  verbs:
  - update
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - ratelimitservices/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - localratelimitconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - localratelimitconfigs/status
  verbs:
  - get
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - localratelimitconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - localratelimitconfigs/status
  verbs:
  - get
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - localratelimits
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - localratelimits/status
  verbs:
  - get
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - localratelimits
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ratelimit.mark43.com
  resources:
  - localratelimits/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-metrics-reader
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "istio-ratelimit-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    manager: {{ .Release.Service }}
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-proxy-role
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    helm.sh/chart: {{ template "istio-ratelimit-operator.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    manager: {{ .Release.Service }}
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
