{{- if .Values.serviceMonitors }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: '*-ratelimit-service'
  endpoints:
  - port: http-statsd-exporter
    path: /metrics

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: redis-cluster
  endpoints:
  - port: http-metrics
    path: /metrics
{{- end }}